spring:
    application:
        name: hanCloud

    profiles:
      active: prod

    jpa:
        open-in-view: false
        show-sql: true
        properties:
          hibernate:
            format_sql: true
            use_sql_comments: true
            highlight_sql: true
            auto_quote_keyword: true
            hbm2ddl:
              auto: create

    servlet:
        multipart:
          enabled: true
          file-size-threshold: 2KB
          max-file-size: 200MB
          max-request-size: 215MB

server:
    port: 9090
    shutdown: graceful

logging:
    level:
      org.springframework.web.multipart: DEBUG

springdoc:
    swagger-ui:
      url: /docs/openapi-3.0.json
      path: /docs/swagger
