spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://121.179.140.28:3306/hanCloud
    username: han_cloud
    password: hans3123!
    driver-class-name: org.mariadb.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 20
      max-total: 20
      max-idle: 20
      min-idle: 20
      test-on-borrow: true
      validation-query: SELECT 1