spring:
    application:
        name: hanCloud
    jpa:
        open-in-view: false
        show-sql: true
        properties:
          hibernate:
            format_sql: true
            use_sql_comments: true
            highlight_sql: true
            auto_quote_keyword: true
            hbm2ddl:
              auto: validate


    datasource:
        url: jdbc:mariadb://121.179.140.28:3306/hanCloud
        username: lilac-soa
        password: nhnacademy123!
        driver-class-name: org.mariadb.jdbc.Driver
        type: org.apache.commons.dbcp2.BasicDataSource
        dbcp2:
          initial-size: 10
          max-total: 10
          max-idle: 10
          min-idle: 10
          test-on-borrow: true
          validation-query: SELECT 1

    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2KB
        max-file-size: 200MB
        max-request-size: 215MB

server:
  port: 9090
  shutdown: graceful

logging:
  level:
    org.springframework.web.multipart: DEBUG